name: Build NEIN LINE IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: python -m pip install --upgrade pip

      - name: Download Decrypted LINE IPA
        run: curl -L -o line_original.ipa "https://pcloud.com"

      - name: Run NEIN Script
        run: |
          mkdir -p output
          python3 tools/main.py --keychain-compat --remove-ads --hide-promotional-tabs line_original.ipa output/NEIN-LINE-secondary.ipa

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NEIN-LINE-IPA
          path: output/NEIN-LINE-secondary.ipa
